version: "3"
services:
  postgres:
    image: postgres:latest
    env_file:
      - ./strapi-app/.env
    volumes:
      - strapi_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  strapi_db:
