name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  setup-build-push:
    name: Build and Push Docker images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Google Container Registry
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Build and push Strapi Docker image
        uses: docker/build-push-action@v2
        with:
          context: ../
          file: ./docker/Dockerfile
          push: true
          tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/strapi:latest

      - name: Build and push PostgreSQL Docker image
        uses: docker/build-push-action@v2
        with:
          image: postgres:14
          push: true

  deploy:
    name: Deploy to GKE
    needs: setup-build-push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure kubectl
        run: gcloud container clusters get-credentials ${{ secrets.GCP_CLUSTER_NAME }} --zone  ${{ secrets.GCP_CLUSTER_ZONE }}

      - name: Deploy to GKE
        run: |
          kubectl apply -f kubernetes-config/
