version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - strapi_db:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  strapi:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        DATABASE_CLIENT: postgres
        DATABASE_NAME: strapi
        DATABASE_HOST: postgres
        DATABASE_PORT: 5432
        DATABASE_USERNAME: strapi
        DATABASE_PASSWORD: strapi
    ports:
      - '1337:1337'
    depends_on:
      - postgres
    volumes:
      - strapi:/app

volumes:
  strapi_db:
  strapi:
